2025-03-02 17:35:41,852 DEBUG: 标签 'test-labe01' 的文章数量: 1
None
2025-03-02 17:35:41,854 DEBUG: 标签 'test' 的文章数量: 0
None
2025-03-02 17:35:41,860 INFO: 成功获取侧边栏数据: 6个分类, 6个标签, 4篇最新文章
None
2025-03-02 17:35:41,861 INFO: Locating template 'blog/index.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/index.html')
None
2025-03-02 17:35:41,871 INFO: Locating template 'blog/base.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/base.html')
None
2025-03-02 17:35:41,877 INFO: Locating template 'blog/includes/messages.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/includes/messages.html')
None
2025-03-02 17:35:41,958 INFO: Locating template 'blog/includes/sidebar.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/includes/sidebar.html')
None
2025-03-02 17:35:42,149 WARNING: Not Found: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
None
2025-03-02 17:35:45,613 INFO: 获取侧边栏数据
None
2025-03-02 17:35:45,615 DEBUG: 分类 '个人博客' 的文章数量: 2
None
2025-03-02 17:35:45,615 DEBUG: 分类 'AI' 的文章数量: 0
None
2025-03-02 17:35:45,616 DEBUG: 分类 '编程' 的文章数量: 1
None
2025-03-02 17:35:45,617 DEBUG: 分类 '科技' 的文章数量: 0
None
2025-03-02 17:35:45,617 DEBUG: 分类 '小说' 的文章数量: 1
None
2025-03-02 17:35:45,618 DEBUG: 分类 '新闻' 的文章数量: 0
None
2025-03-02 17:35:45,619 DEBUG: 标签 '个人博客' 的文章数量: 2
None
2025-03-02 17:35:45,620 DEBUG: 标签 'AI' 的文章数量: 1
None
2025-03-02 17:35:45,621 DEBUG: 标签 'Python' 的文章数量: 2
None
2025-03-02 17:35:45,622 DEBUG: 标签 '励志' 的文章数量: 1
None
2025-03-02 17:35:45,623 DEBUG: 标签 'test-labe01' 的文章数量: 1
None
2025-03-02 17:35:45,625 DEBUG: 标签 'test' 的文章数量: 0
None
2025-03-02 17:35:45,626 INFO: 成功获取侧边栏数据: 6个分类, 6个标签, 4篇最新文章
None
2025-03-02 17:35:45,626 INFO: Locating template 'blog/post.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/post.html')
None
2025-03-02 17:35:45,810 WARNING: Not Found: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
None
2025-03-02 17:35:49,070 INFO: Locating template 'auth/login.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/auth/login.html')
None
2025-03-02 17:35:49,073 INFO: Locating template 'blog/layout.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/layout.html')
None
2025-03-02 17:35:49,076 INFO: Locating template 'macros/csrf.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/macros/csrf.html')
None
2025-03-02 17:35:49,078 INFO: Locating template 'blog/includes/nav.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - /data/myblog/app/templates
       -> found ('/data/myblog/app/templates/blog/includes/nav.html')
None
2025-03-02 17:35:49,085 ERROR: 登录过程中发生错误: Could not build url for endpoint 'auth.register'. Did you mean 'auth.login' instead?
Traceback (most recent call last):
  File "/data/myblog/app/controllers/auth/__init__.py", line 102, in login
    return render_template('auth/login.html', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/data/myblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/myblog/app/templates/auth/login.html", line 1, in top-level template code
    {% extends "blog/layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/app/templates/blog/layout.html", line 22, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/app/templates/auth/login.html", line 34, in block 'content'
    <a href="{{ url_for('auth.register') }}">没有账号？立即注册</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.register'. Did you mean 'auth.login' instead?

None
2025-03-02 17:35:49,088 ERROR: Exception during request: Could not build url for endpoint 'auth.register'. Did you mean 'auth.login' instead?
None
2025-03-02 17:36:36,280 ERROR: 登录过程中发生错误: Could not build url for endpoint 'auth.register'. Did you mean 'auth.login' instead?
Traceback (most recent call last):
  File "/data/myblog/app/controllers/auth/__init__.py", line 102, in login
    return render_template('auth/login.html', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/data/myblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/data/myblog/app/templates/auth/login.html", line 1, in top-level template code
    {% extends "blog/layout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/app/templates/blog/layout.html", line 22, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/app/templates/auth/login.html", line 34, in block 'content'
    <a href="{{ url_for('auth.register') }}">没有账号？立即注册</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/myblog/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.register'. Did you mean 'auth.login' instead?

None
2025-03-02 17:36:36,283 ERROR: Exception during request: Could not build url for endpoint 'auth.register'. Did you mean 'auth.login' instead?
None
